### ISSUE TITLE
Consider updating?

### ISSUE THREAD

**Issue by Firetheft** [tianlang0704/ComfyUI-StableProjectorzBridge#8] opened 2024-09-06 07:19 UTC
No longer available

**Comment by tianlang0704** [comment] 2024-09-12 09:51
The author of Projectorz is considering support for ComfyUI natively, I think that will be a better option for all, with more functions and more stability. If he does it recently, this repo will be unnecessary and probably removed.

**Comment by tianlang0704** [comment] 2024-11-03 09:45
I just got back, sorry for the very late response, I don't have much time to work on this. 
StableProjectorz author helped on fixing the problem, I just merged the code and updated the version.

**Comment by Imyamoe** [comment] 2024-11-03 15:17
> I just got back, sorry for the very late response, I don't have much time to work on this. StableProjectorz author helped on fixing the problem, I just merged the code and updated the version.

Thanks for your contribution! But unfortunately it is not fixing the API issue. Something got broken in the latest Comfyui update. IgorAherne also mentioned on Discord he is not able to fix it too

**Comment by tianlang0704** [comment] 2024-11-13 09:13
Let me have a dig into the Discord messages. Also, could you give a bit more information on what the API issue is about? Thanks. @Imyamoe

**Comment by Imyamoe** [comment] 2024-11-14 15:15
> Let me have a dig into the Discord messages. Also, could you give a bit more information on what the API issue is about? Thanks. @Imyamoe

Unfortunately I don't know why it's actually happening. Since the cmd window is not even showing any connection attempt from the Projectorz. And I wasn't able to find any logs on the Projectorz side. The connection attempt just fails silently. The fact is that it started happening upon the ComfyUI last core update

And thank you again for paying attention to the issue!

**Comment by manzonif** [comment] 2024-11-20 09:22
Seems to be related to this:

**_# ComfyUI Internal Routes

All routes under the `/internal` path are designated for **internal use by ComfyUI only**. These routes are not intended for use by external applications may change at any time without notice.**


I tried these changes and it seems to work.

```python
@PromptServer.instance.internal_routes.routes.get('/sysinfo')
async def sysinfo_handler(request):
    return get_json_response('sysinfo.json')

@PromptServer.instance.internal_routes.routes.get('/ping')
async def ping_handler(request):
    return web.Response()
 ```

**Comment by Imyamoe** [comment] 2024-11-20 23:53
> Seems to be related to this:
> 
> **_# ComfyUI Internal Routes
> 
> All routes under the `/internal` path are designated for **internal use by ComfyUI only**. These routes are not intended for use by external applications may change at any time without notice.**
> 
> I tried these changes and it seems to work.
> 
> ```python
> @PromptServer.instance.internal_routes.routes.get('/sysinfo')
> async def sysinfo_handler(request):
>     return get_json_response('sysinfo.json')
> 
> @PromptServer.instance.internal_routes.routes.get('/ping')
> async def ping_handler(request):
>     return web.Response()
> ```

I can confirm, it is working in 2.0.4 and in 2.1.8! Totally worth a pull request. Thank you!

**Closed as completed** 2024-11-28 11:21 UTC

**Comment by tianlang0704** [comment] 2024-11-28 11:25
@Imyamoe @manzonif Updated, Thanks a lot!
